/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_snbc_ctoso_Memtest.h"
extern simple_memtest();

JNIEXPORT jint JNICALL Java_com_snbc_ctoso_Memtest_simpleMemtest
  (JNIEnv *env, jclass obj){
    return simple_memtest();
}
