/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_snbc_ctoso_Memtest */

#ifndef _Included_com_snbc_ctoso_Memtest
#define _Included_com_snbc_ctoso_Memtest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_snbc_ctoso_Memtest
 * Method:    simpleMemtest
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_snbc_ctoso_Memtest_simpleMemtest
  (JNIEnv *, jclass);

JNIEXPORT jstring JNICALL Java_com_snbc_ctoso_Memtest_rtcGetTime
        (JNIEnv *, jclass, jstring);

JNIEXPORT jint JNICALL Java_com_snbc_ctoso_Memtest_rtcSetTime
        (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
