/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_zhougaoxiong_sodemo_Hello */

#ifndef _Included_com_example_zhougaoxiong_sodemo_Hello
#define _Included_com_example_zhougaoxiong_sodemo_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_zhougaoxiong_sodemo_Hello
 * Method:    getAdd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_zhougaoxiong_sodemo_Hello_getAdd
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
