/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_zhougaoxiong_sodemo_Helloo */

#ifndef _Included_com_example_zhougaoxiong_sodemo_Helloo
#define _Included_com_example_zhougaoxiong_sodemo_Helloo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_zhougaoxiong_sodemo_Helloo
 * Method:    getAdd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_zhougaoxiong_sodemo_Helloo_getAdd
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
